package com.soundhelix.misc;

import java.util.Set;

/**
 * Represents a harmony. A harmony defines the chord sections and the chords to use for every tick. Instances of this class must consistently return
 * their results.
 * 
 * Harmonies are usually generated by HarmonyEngines.
 * 
 * @author Thomas Schuerger (thomas@schuerger.com)
 */

public interface Harmony {
    /**
     * Returns the chord to use at the specified point in time. Within the valid tick interval this must be non-null (i.e., each tick must define a
     * chord).
     * 
     * @param tick the tick
     * 
     * @return the Chord (or null if the tick is out of range)
     */

    Chord getChord(int tick);

    /**
     * Returns the set of tags for the given tick. Within the valid tick interval this must be non-null. If a tick doesn't define any tags, an empty
     * set must be returned rather than null.
     * 
     * @param tick the tick
     * 
     * @return the set of tags (or null if the tick is out of range)
     */

    Set<String> getTags(int tick);

    /**
     * Returns the number of ticks the current chord will be played from the given tick position before the chord will change or the song will end
     * (whichever happens first). This requirement is strict, i.e., the chord must not change before the returned number of ticks and it must change
     * directly afterwards or the song must end. For a valid tick parameter, the return value must always be positive.
     * 
     * @param tick the tick
     * 
     * @return the number of ticks before the next chord change
     */

    int getChordTicks(int tick);

    /**
     * Returns the number of ticks the current set of tags stays constant until the set of tags changes or the song will end (whichever happens
     * first). This requirement is strict, i.e., the set of tags must not change before the returned number of ticks and it must change directly
     * afterwards or the song must end. For a valid tick parameter, the return value must always be positive.
     * 
     * @param tick the tick
     * 
     * @return the number of ticks before the next change of tags
     */

    int getTagTicks(int tick);

    /**
     * Returns the number of ticks the current chord section will be played from the given tick position before the next chord section will begin or
     * the song will end. This method can be used to check when special processing (like adding rhythm fill-ins) can be done. For standard chord
     * sections, the total length of the chord section should be used. For a valid tick parameter, the return value must always be positive.
     * 
     * @param tick the tick
     * 
     * @return the number of ticks before the next chord section begins or the song will end
     */

    int getChordSectionTicks(int tick);
}
