package com.soundhelix.misc;

import com.soundhelix.component.player.Player;

/**
 * Defines the context of a song. During song generation, the context is enriched with information.
 * Each of the fields can only be set to at most once.
 * 
 * @author Thomas Schuerger (thomas@schuerger.com)
 */

public class SongContext {
    /** The song's random seed (null if a song is generated by supplying a song name). */
    private Long randomSeed;

    /** The song name. */
    private String songName;

    /** The structure. */
    private Structure structure;

    /** The harmony. */
    private Harmony harmony;

    /** The activity matrix. */
    private ActivityMatrix activityMatrix;

    /** The arrangement. */
    private Arrangement arrangement;
    
    /** The player. */
    private Player player;

    public Long getRandomSeed() {
        return randomSeed;
    }

    public void setRandomSeed(Long randomSeed) {
        this.randomSeed = randomSeed;
    }

    public String getSongName() {
        return songName;
    }

    public void setSongName(String songName) {
        if (this.songName != null) {
            throw new IllegalArgumentException("songName already set");
        }
        
        this.songName = songName;
    }

    public Structure getStructure() {
        return structure;
    }

    public void setStructure(Structure structure) {
        if (this.structure != null) {
            throw new IllegalArgumentException("structure already set");
        }

        this.structure = structure;
    }

    public Harmony getHarmony() {
        return harmony;
    }

    public void setHarmony(Harmony harmony) {
        if (harmony == null) {
            throw new RuntimeException("harmony already set");
        }

        this.harmony = harmony;
    }

    public ActivityMatrix getActivityMatrix() {
        return activityMatrix;
    }

    public void setActivityMatrix(ActivityMatrix activityMatrix) {
        if (this.activityMatrix != null) {
            throw new IllegalArgumentException("activityMatrix already set");
        }

        this.activityMatrix = activityMatrix;
    }

    public Arrangement getArrangement() {
        return arrangement;
    }

    public void setArrangement(Arrangement arrangement) {
        if (this.arrangement != null) {
            throw new IllegalArgumentException("arrangement already set");
        }
        
        this.arrangement = arrangement;
    }

    public Player getPlayer() {
        return player;
    }

    public void setPlayer(Player player) {
        if (this.player != null) {
            throw new IllegalArgumentException("player already set");
        }

        this.player = player;
    }
}
